cbox: add basic option parsing
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

diff --git a/cbox.in b/cbox.in
--- a/cbox.in
+++ b/cbox.in
@@ -3,6 +3,84 @@
 set -e
 
 # cbox hook dir
-[ -z "$(CBOXDATA)" ] && CBOXDATA="HOOKDIR"
+[ -z "$CBOXDATA" ] && CBOXDATA="HOOKDIR"
+
+function print_usage() {
+	echo "$(basename $0) usage:"
+	echo ""
+}
+
+function is_integer() {
+    [ "$1" -eq "$1" ] > /dev/null 2>&1
+    return $?
+}
+
+# parse command line options
+#
+# c -> cluster name (clustername)
+# h -> help
+# n -> number of nodes (numnodes)
+# t -> type (clustertype)
+# v -> verbose
+
+# clear envvars
+clustername=""
+numnodes=""
+clustertype=""
+verbose=""
+
+while getopts ":c:hn:t:v" optflag; do
+	case "$optflag" in
+	c)
+		clustername="$OPTARG"
+		;;
+	n)
+		numnodes="$OPTARG"
+		! is_integer $numnodes && {
+			echo "ERROR: number of nodes needs to be an integer (min 2, max 16)"
+			exit 1
+		}
+		if [ "$numnodes" -lt "2" ] || [ "$numnodes" -gt "16" ]; then
+			echo "ERROR: invalid number of nodes specified (min 2, max 16)"
+			exit 1
+		fi
+		;;
+	t)
+		clustertype="$OPTARG"
+		if [ "$clustertype" != "cman" ] && \
+		   [ "$clustertype" != "pacemaker" ]; then
+			echo "ERROR: cluster type has to be cman or pacemaker"
+			exit 1
+		fi
+		;;
+	v)
+		verbose="yes"
+		;;
+	h)
+		print_usage
+		exit 0
+		;;
+	\?|:)
+		print_usage
+		exit 1
+		;;
+	esac
+done
+
+[ -z "$clustername" ] && {
+	echo "ERROR: please specify the clustername"
+	print_usage
+	exit 1
+}
+
+[ -z "$numnodes" ] && {
+	echo "INFO: no number of nodes specified, default to 2"
+	numnodes=2
+}
+
+[ -z "$clustertype" ] && {
+	echo "INFO: no cluster type defined, default to cman"
+	clustertype=cman
+}
 
 exit 0
