Add warning of death
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

diff --git a/cbox.in b/cbox.in
--- a/cbox.in
+++ b/cbox.in
@@ -96,6 +96,34 @@ while getopts ":c:hm:n:or:t:" optflag; do
 	esac
 done
 
+## ask question
+echo "***** WARNING *****"
+echo ""
+echo "cbox is an experimental script to build virtual TEST cluster"
+echo "and it performs actions and configurations that might not be"
+echo "considered safe on both the host and the guests."
+echo "Please abort the execution now unless you fully understand"
+echo "what you are doing."
+echo "The resulting setup has to be used only for TESTING."
+echo "By all mean, do NOT place this cluster into production."
+echo ""
+echo "cbox can only be executed once on each host. Multiple execution"
+echo "will results in a royal mess."
+echo ""
+echo "***** END OF WARNING *****"
+echo ""
+echo "YOU HAVE BEEN WARNED"
+echo ""
+echo "If you agree, and want to proceed, please type:"
+echo "Yes, I fully understand the risks of what I am doing"
+echo ""
+read -p "type here: " ans
+
+[ "$ans" = "Yes, I fully understand the risk of what I am doing" ] || {
+	echo "Wise choice.. or you simply didn't type it right"
+	exit 0
+}
+
 [ ! -d "$cboxdatadir" ] && {
 	echo "ERROR: no valid data directory specified: $cboxdatadir"
 	exit 1
