hooks: cleanup tempdir/tempfiles and add verbose logging
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

diff --git a/hooks/03_host_net_setup b/hooks/03_host_net_setup
--- a/hooks/03_host_net_setup
+++ b/hooks/03_host_net_setup
@@ -2,20 +2,28 @@
 
 set -e
 
+echo "Starting libvirtd service"
+
 service libvirtd start
 
-virsh net-list |grep -q ^cluster && exit 0
+echo "Checking if cluster virt net already exists"
+virsh net-list |grep -q ^$cboxclustername-bridge && {
+	echo "$cboxclustername-bridge virt net detected: aborting"
+	exit 1
+}
 
+echo "Making a backup copy of main host /etc/hosts to /etc/hosts.cbox"
 cp /etc/hosts /etc/hosts.cbox
 
-tempfile="$(mktemp)"
+echo "Generating libvirt $cboxclustername-bridge xml template"
+tempfile="$cboxtempdir/libvirt-net.xml"
 
 cat > "$tempfile" << EOF
 <network>
-  <name>cluster</name>
+  <name>$cboxclustername-bridge0</name>
   <uuid>$(uuidgen)</uuid>
   <forward mode='nat'/>
-  <bridge name='cluster-bridge0' stp='off' delay='0'/>
+  <bridge name='$cboxclustername-bridge0' stp='off' delay='0'/>
   <ip address='192.168.123.254' netmask='255.255.255.0'>
     <dhcp>
       <range start='192.168.123.1' end='192.168.123.253'/>
@@ -23,6 +31,7 @@ EOF
 
 for i in $(seq 1 $cboxnumnodes); do
 	echo "      <host mac='54:52:00:00:00:$(printf '%x' $i)' name='$cboxclustername-node$i' ip='192.168.123.$i' />" >> "$tempfile"
+	echo "Adding 192.168.123.$i $cboxclustername-node$i to main host /etc/hosts"
 	echo "192.168.123.$i $cboxclustername-node$i" >> /etc/hosts
 done
 
@@ -32,10 +41,17 @@ cat >> "$tempfile" << EOF
 </network>
 EOF
 
+echo "XML result:"
+cat "$tempfile"
+
+echo "Updating main host /etc/hosts"
 echo "192.168.123.254 $cboxclustername-host" >> /etc/hosts
 
+echo "Adding $cboxclustername-bridge to libvirt"
 virsh net-define "$tempfile"
+echo "Setting $cboxclustername-bridge to start automatically"
 virsh net-autostart cluster
+echo "Starting $cboxclustername-bridge"
 virsh net-start cluster
 
 rm -f "$tempfile"
