Better verification of host booting correctly
Signed-off-by: Fabio M. Di Nitto <fdinitto@redhat.com>

diff --git a/hooks/61_guest_start_first b/hooks/61_guest_start_first
--- a/hooks/61_guest_start_first
+++ b/hooks/61_guest_start_first
@@ -6,6 +6,16 @@ echo "Starting main guest"
 
 virsh start $cboxclustername-node1
 
-sleep 60
+max=60
+count=0
+while ! ssh $cboxclustername-node1 -i .ssh/id_rsa_$cboxclustername -o StrictHostKeyChecking=no "sleep 5"; do
+	echo "Wating for $cboxclustername-node1 to boot"
+	sleep 5
+	[ "$max" -eq "$count" ] && {
+		echo "ERROR: $cboxclustername-node1 did not respond to ssh after 300 seconds"
+		exit 1
+	}
+	count=$((count+1))
+done
 
 exit 0
